export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const CREATE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
